## YAML Template.

server:
    port: 8089 
spring:
   cloud:    
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
          cors-configurations:
             '[/**]':
             allowed-origins: "*"
             allowed-methods: "*"
             allowed-headers: "*"
             allow-credentials: true
# spring:
#   cloud:
#     gateway:
#       routes:
#       - id: security
#         uri: 'http://localhost:8082/'
#         predicates:
#         - path: '/security/**'
#       - id: student
#         uri: http://localhost:8082/
#         predicates:
#         - path: "/student/**"